### ISSUE TITLE
video tutorial?

### ISSUE THREAD

**Issue by b-e-y** [adi-panda/Kuebiko#1]
hello, i really like your work!
but im struggling to figure out how to make everything work.. 
is there a way you can make a video tutorial on how to setup everything and make this work?

**Comment by adi-panda** [comment]
I'm actually making a video about this project, but it's not really a tutorial, if you message me on discord I can help you out awdii#2034.

**Comment by b-e-y** [comment]
thanks, i'll dm me you there, my discord is bey#1014

**Comment by adi-panda** [comment]
Added tutorial.
