### ISSUE TITLE
Audio starts but it doesnt end the speechs and cut

### ISSUE THREAD

**Issue by ManuelMultiverse** [adi-panda/Kuebiko#10]
[0000025d41d7fae0] mmdevice audio output error: cannot initialize COM (error 0x80010106)

**Comment by Scatogaro** [comment]
I have the same problem now, the thing is, I did not had this problem in the beginning, so maybe its because some library we installed afterwards, I hope this works as a clue for you

**Comment by Scatogaro** [comment]
> I have the same problem now, the thing is, I did not had this problem in the beginning, so maybe its because some library we installed afterwards, I hope this works as a clue for you

Update: I still couldn't resolve it, but I read in other websites that the problem becomes less evident in certain older versions of VLC, and it kinda works, the audio that gets cut is way more less but it is still there, still, something I got to get around this as a temporal fix is putting in the prompt to always end the sentences with "--", so the end cut just ends after the TTS heards completely, the version of VLC that I tried is the 3.0.5 64 bits, I hope this temporal fix gets useful to you

**Comment by Scatogaro** [comment]
update: Now I just noticed that using VLC with this error makes it so the use of the VB Virtual Cable makes the program unable to play the audio as an error, so we really need to fix this VLC compatibilty issue or have someone who knows how to modify the code so it stops using VLC and changes it to another one

**Comment by Adolfiux** [comment]
I have the same problem, yesterday was working great, I don't know what could be.

**Comment by Adolfiux** [comment]
Update: I just uninstall all the PIP packages (command: pip list), just uninstall all using this command: pip uninstall package-name, after this uninstall and install miniconda3, then run the "pip install -r requirements.txt" and that's it.

**Comment by caesarakalaeii** [comment]
I'll call this done now, for future reference I'd recommend using speaker bot.
