### ISSUE TITLE
How can I use the Sandford Alpaca model from a locally run computer instead of Open AI?

### ISSUE THREAD

**Issue by dontaco2000** [adi-panda/Kuebiko#12]
Hi, I have had a great time with this project! I was wondering if there was a way to replace the Open AI response fetch with a Stanford Llama model that I would locally run on a networked computer. That would be class because it would allow me to create my own filter allowing the Vtuber to be a bit more risque than what Open AI allows. Thank you.

**Comment by adi-panda** [comment]
I am planning on making a tutorial for this... stay tuned.

**Comment by Adolfiux** [comment]
Please,!!!

**Comment by dontaco2000** [comment]
Hell yeah dude! Thanks!
