### ISSUE TITLE
A few different modes.

### ISSUE THREAD

**Issue by dontaco2000** [adi-panda/Kuebiko#15]
I know I am cramming the box and I'm sorry about that. I do want to get out the things I would like to see in future versions of this project. I have a few feature ideas that would probably require a true/false toggle. I came across the desire for these features as I am using the AI VTuber as a co-streamer.

- I would like it to be able to be listening to closed captions to activate conversations with me. I have closed captions on my mic and I can also get it to work for discord too through OBS to have twitch display, I just have to tell the captions what channel to listen to. Ideally, it would listen when it's name was mentioned and then listen for 30 seconds after the last response to continue a conversation and then turn itself off if there is 30 seconds of silence. Maybe 30 seconds is too long but I am kind of spitballing here with that.

- I would also like it to start it's own small talk conversations if possible when there has been no action on closed caption for like a minute. Maybe tell a story about it's day or something that happened to them that was funny. I mean I know part of that belongs in the prompt but it would need to be programmed in to activate those kind of conversations.

- I also had a crazy idea of the prompt temperature changing to match the "mood" of the conversation. If people are being mean or she doesn't like the conversation her responses are more rigid and if she is in a "good mood" or people are just being nice, she can give more loose and unpredictable responses. I noticed that she has positive and negative responses, perhaps after the response if it contains negative words, it does a -.1 and if it has positive words in the response it's +.1 otherwise it is 0 on the change. I'm sure of all three, this one would be the hardest to execute so, you can tell me to get bent on this one lol. It would be cool if it could though. 

If you ever want to audit what I'm doing, drop by my stream sometime.

**Comment by Adolfiux** [comment]
whats your user on twitch??

**Comment by dontaco2000** [comment]
thetankwilliams

**Comment by caesarakalaeii** [comment]
Point 1 is now available, however only through Windows Speech-to-Text.
Point 2 Could be added, using a simple timer, let me know if you're still interested.
Point 3 is very hard with the current setup, but might be possible to some extend through your System Prompt.
