### ISSUE TITLE
Add word filter?

### ISSUE THREAD

**Issue by yoshuzx** [adi-panda/Kuebiko#16]
Hi, I would like to add a word filter. Is it possible?
I have read the OpenAI documentation about moderation, but I don't understand how to implement it.
Can someone help me? Thank you in advance.

**Comment by TheSoftDiamond** [comment]
I'm maintaining a [fork ](https://github.com/TheSoftDiamond/Kazushin) of this project with this implementation. But essentially, when you grab the user's message, you want to compare the string against a list containing the words you do not want.

**Comment by caesarakalaeii** [comment]
I can add a simple word filter however, I'm unsure what you want to be filtered.
Do you want to filter the input (Chat messages) or the output (ChatGPT response)

**Comment by caesarakalaeii** [comment]
Added a simple filter for Chat messages now
