### ISSUE TITLE
"How to fix 'FileNotFoundError: Could not find module libvlc.dll' when running Python script for Twitch chatbot on GitHub?"

### ISSUE THREAD

**Issue by ainzlpnoresponse** [adi-panda/Kuebiko#18]
"Hi, I encountered an error when running the command 'python main.py' for the Twitch chatbot. Specifically, I got a 'FileNotFoundError' saying that the 'libvlc.dll' module could not be found in the directory specified. I checked my setup and it seems like the module is indeed missing. Can someone please advise on how to resolve this issue? Thank you!"
![image](https://user-images.githubusercontent.com/58736786/231667164-f21dd1c7-1390-4094-aeeb-d48f7170801a.png)

The method I have tried but not useful (same error):
1.  reinstalling the vlc library by running the following command in your command prompt:
`pip uninstall python-vlc`
`pip install python-vlc`
2.  manually installing the vlc library by downloading it from the website https://www.dll-files.com/libvlc.dll.html for Version 3.0.8.0 into "Kuebiko-main" folder

**Comment by miscla** [comment]
```
import os
os.add_dll_directory(r'C:\Program Files\VideoLAN\VLC')

import vlc
```

try to change to this code for add your vlc folder

**Comment by Adolfiux** [comment]
Do u have the lasted VLC installed on windows?

**Comment by ainzlpnoresponse** [comment]
Yes, that's my personal issue that doesnt install VLC properly, I install it from official site, thank you everyone!
