### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by chimmykk** [adi-panda/Kuebiko#19]
Chracter Mouth open and follow according to the response but sound is not coming

**Comment by adi-panda** [comment]
If you're using VB-Audio Cable, you might need to turn on listening to the output on OBS, as outlined in this comment from the original video: 
For anyone wondering why you can't hear the sound output from OBS Studio, you need to change the Desktop Audio --> click the three dots --> Advanced Audio Properties -->  change Audio Monitoring to other than Monitor Off. For example, if you record with the Monitor and Output on, both sounds (in this case, monitor and speaker) will be recorded.

**Comment by caesarakalaeii** [comment]
Imma close this too
