### ISSUE TITLE
Google cloud !!

### ISSUE THREAD

**Issue by BLINK-SG** [adi-panda/Kuebiko#2]
can you please provide alternative to google cloud api.

**Comment by MrBlackReal** [comment]
You can use the [TTS python](https://pypi.org/project/TTS/) library it might take a while to convert but it isn't that hard.

**Comment by adi-panda** [comment]
> You can use the [TTS python](https://pypi.org/project/TTS/) library or [edge tts](https://pypi.org/project/edge-tts/) it might take a while to convert but it isn't that hard.

I endorse this response.

**Comment by Vinventive** [comment]
Could someone please give us some advice on how to set up AWS TTS Voices as alternative? I would appreciate it.

**Comment by CookieSuzuki** [comment]
A alternative that can be run for locally and for free would be [pyttsx3](https://pypi.org/project/pyttsx3/), which is a simple and easy to use text to speech program. Though it doesn't feature vocal modulation, it is straightforward to implement without interfering with other code. If you see error messages, you should be able to ignore them. To use pyttsx3, you can import it at the beginning of your Python code (main.py) with your other imports, and then add the rest of the pyttsx3 code on line 56 (I would put a space between the code so it actually goes on line 57 but that's personal preference and a unnecessary step). The code initializes the engine, sets the volume and speed, chooses a voice (0=male 1=female), and then it will say the reply to chat.

```
        import pyttsx3
```
```
        engine = pyttsx3.init()
        volume = engine.getProperty("volume")
        print("volume is {0}".format(volume))
        engine.setProperty("volume", 1)
        rate = engine.getProperty('rate')
        engine.setProperty('rate', rate+1)
        voices = engine.getProperty("voices")
        engine.setProperty("voice", voices[1].id)
        engine.say(response)
        engine.runAndWait()
```

**Comment by GabGabchan** [comment]
I get this message everytime I generate an output:
volume is 1.0
Traceback (most recent call last):
  File "C:\Users\gab\miniconda3\lib\site-packages\twitchio\client.py", line 208, in wrapped
    await func(*args)
  File "C:\Users\gab\Kuebiko-main\main.py", line 67, in event_message
    client = texttospeech.TextToSpeechClient()
NameError: name 'texttospeech' is not defined

**Comment by MrBlackReal** [comment]
It says:
```
File "C:\Users\gab\Kuebiko-main\main.py", line 67, in event_message
client = texttospeech.TextToSpeechClient()
NameError: name 'texttospeech' is not defined
```

Your field "texttospeech" is not defined make sure you have it imported.

**Comment by caesarakalaeii** [comment]
You can now use speaker bot to use any other supported TTS service.
