### ISSUE TITLE
How to make the vtuber take action according to ChatGPT's instructions ?

### ISSUE THREAD

**Issue by breakenknife** [adi-panda/Kuebiko#20]
hello, I want chatgpt to play various roles and include simple action instructions in the generated responses. Then the VTuber takes action according to the instructions. like:

me: can you turn around?
chatgpt: yes, i can (turn around body).
vtuber voice: yes, ican.
vtuber action : turn around

**Comment by caesarakalaeii** [comment]
You could technically achieve that by Prompt engineering, your output includes an expression or action.

Simplest example for that would be:
" ALWAYS answer in the following format: {"message": RESPONSE, "action": ACTION}. You have the following actions to choose from: {Action1, etc...}

However that is not necessarily stable, another more complicated approach would be sentiment analysis.

**Comment by caesarakalaeii** [comment]
I'll close this for now too
