### ISSUE TITLE
AI eventually forgets about the info given in prompt_chat.txt

### ISSUE THREAD

**Issue by Ruhrev** [adi-panda/Kuebiko#22]
After a while, because of all the conversations going on. The AI forgets about the initial information set by prompt_chat.txt.

Is there a good way around this?

I tried adding a very makeshift way of pushing the prompt in again after every conversation, but that just made me get token errors, because it's adding too much to it. I'm absolutely doing it the wrong way, because I'm not too good at this stuff.

```python
 async def event_message(self, message):
        ...
        ...
        ...
        Bot.conversation.append(
            {'role': 'system', 'content': open_file('prompt_chat.txt')})
        print('------------------------------------------------------')
        os.remove(audio_file)

        # Since we have commands and are overriding the default `event_message`
        # We must let the bot know we want to handle and invoke our commands...
        await self.handle_commands(message)
```

```bash api_requestor.py", line 679, in _interpret_response_line
raise self.handle_error_response(openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4184 tokens (3784 in the messages, 400 in the completion). Please reduce the length of the messages or completion.
```

I'm basically trying to find a way to inject the prompt chat info now and then, without it ruining everything. Piling it up or what have you. Because clearly the terrible way I'm going about it, is not working.

Thanks for this project by the way, truly appreciate it. Having so much fun with it.

**Comment by adi-panda** [comment]
Im not really sure but Ive found that it tends to adhere to the prompt more on the davinci model which you can find in the davinci branch.

**Comment by TheSoftDiamond** [comment]
@Ruhrev I have been working on a fork of this project called [Kazushin](https://github.com/TheSoftDiamond/Kazushin) which implements this kind of feature.

In my code,
        ```
if len(user_context) > CONVERSATION_LIMIT:
            try:
                user_context.pop(1) #Pull the SECOND element only. Must be at least 1, so that AI keeps context
            except IndexError:
                print("IndexError on pop of user context")
```

this block was what I created to help pull only the second element out so that context is kept. if you choose to use your original project, you may need to code in such a statement.
