### ISSUE TITLE
on the master branch errors

### ISSUE THREAD

**Issue by doctor-stinkinbear** [adi-panda/Kuebiko#27]
Hey! saw there was some updates on the master branch so tried to grab them - Couldn't find the google application credentials area - was also getting this error - 

   File "C:\Users\jack\Desktop\AI Streamer 4\Kuebiko-master\main.py", line 3, in <module>
    from chat import *
  File "C:\Users\jack\Desktop\AI Streamer 4\Kuebiko-master\chat.py", line 10, in <module>
    with open(os.path.expanduser('~') + '/.kuebikoInfo.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jack/.kuebikoInfo.json'

**Comment by adi-panda** [comment]
Sorry, I'm working on some updates with adding a UI Interface to the program, for now, ignore the master branch, but if you are curious you can try building the UI using tauri in the `kuebiko_v` folder.

**Comment by doctor-stinkinbear** [comment]
ayyy no probs thx for the reply! I looked at that folder but it's a bit advanced for my pea-sized brain! i really don't know anything about code hahaha xD excited to see you working on stuff though, big ups <3

**Comment by caesarakalaeii** [comment]
Should be fixed with using Speaker Bot
