### ISSUE TITLE
Can the process be triggered by a command or word written in the chat?

### ISSUE THREAD

**Issue by MauricioBlanch** [adi-panda/Kuebiko#29]
Hi, please I was wondering if I can lock the process so my avatar would only speak when asked, I can't understand or find the solution for this, maybe is only adding an if, but I'm not good at it.

**Comment by caesarakalaeii** [comment]
Yes you can, either utilizing the command functionality or simply by checking the message content for a "name in message.content" statement.

**Comment by caesarakalaeii** [comment]
Added the feature
