### ISSUE TITLE
gpt-3.5-turbo

### ISSUE THREAD

**Issue by rpgsolomaker** [adi-panda/Kuebiko#3]
Does anyone know how to implement gpt-3.5 to the code? seems like a better and cheaper option for this project than previous openai models. Thank you.

**Comment by CodeWithSwastik** [comment]
I have written a version that uses gpt-3.5-turbo, you can find it in the chat.py file in this repository: https://github.com/CodeWithSwastik/ProjectX

Direct link: https://github.com/CodeWithSwastik/ProjectX/blob/main/chat.py

**Comment by KoroVT** [comment]
Im interested on knowing this as well, if anyone has a way to do it.

**Comment by adi-panda** [comment]
Thanks to @GabrielAlmeida1701 , GPT 3.5 is now supported! Enjoy!
