### ISSUE TITLE
Discord Intergration

### ISSUE THREAD

**Issue by ittzApollo** [adi-panda/Kuebiko#31]
Hey,

I don't suppose you could rework this to instead of being for twitch, it is integrated with Discord.

As in....

It is linked to a bot that we can create in the Discord Dev Portal, it joins a channel when the Host joins and it uses Speech recognition to listen to what that person says and then responds text to speech.

This would be extremely helpful if you have the time to look in to this.

Thank you.

**Comment by caesarakalaeii** [comment]
I doubt that it's the scope of this Project, but using discord.py you can very easily achieve chat compatibility.
However afaik discord does not allow for Voice access via API yet.
