### ISSUE TITLE
FATAL:  Exception in main loop: [WinError 1225] The remote computer refused the network connection

### ISSUE THREAD

**Issue by paw29** [adi-panda/Kuebiko#41]
I tried running main.py after debugging some code to update with openai's latest version. It gives this error:
 Info:  Sending Packet with ID 22320
 FATAL:  Exception in main loop: [WinError 1225] The remote computer refused the network connection

it replies on the first prompt then ignores after that.

**Comment by Ololo8888** [comment]
faced the same problem

**Comment by paw29** [comment]
bump

**Comment by Pureblue12** [comment]
Did you ever resolve this issue?
