### ISSUE TITLE
How can we make the AI remember the chat history?

### ISSUE THREAD

**Issue by MezereonXP** [adi-panda/Kuebiko#6]
It is an awesome project!

I am trying to implement a powerful AI-VTuber and I find this amazing repo.

But if we use the GPT-3 API, we can not fine-tune the model with the chat history.

Though, we could add the history to the prompt text. 

It is still a limitation for handling a long chat history.
(OpenAI will limit the length of context)

In my opinion, we should keep a local trainable model for archiving a more real AI VTuber?

**Comment by Dixce** [comment]
Is there any way that I can have a better vocabulary?
Maybe a little freer and saying inappropriate things from time to time, it becomes boring that she is always correct and respectful

**Comment by mikeszig** [comment]
This may require the use of a local model. Maybe something like Stanford LLaMA, BERT or ChatterBot are some of the ones I can think of right now.

**Comment by caesarakalaeii** [comment]
You can now fine-tune GPT-Models, see here: https://platform.openai.com/docs/guides/fine-tuning , using a different Model with a higher context and setting the CONVERSATION_LIMIT variable to a higher number will work too, how ever there's currently no persistence for the chat.
