### ISSUE TITLE
Is there any way that I can have a better vocabulary? l

### ISSUE THREAD

**Issue by Dixce** [adi-panda/Kuebiko#8]
Maybe a little freer and saying inappropriate things from time to time, it becomes boring that she is always correct and respectful

**Comment by KoroVT** [comment]
Sadly since it's based from ChatGPT itself, the vocabulary it's already predetermined, it's already made with "laws" in it's program.

**Comment by MezereonXP** [comment]
Maybe you could add some personal descriptions to the prompt text or adjust the temperature coefficient to make some randomness.

**Comment by caesarakalaeii** [comment]
Feel free to experiment using "Jailbreaks", however these are bound to be fixed. Otherwise I'd recommend different Models entirely.
